# Generated by Django 3.2 on 2021-04-18 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('placesapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='image',
        ),
    ]
